# Generated by Django 2.2.1 on 2019-06-23 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_articlepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticlePost',
        ),
    ]
